import jsPDF from 'jspdf'
import Papa from 'papaparse'

export const exportToPDF = (report) => {
  const doc = new jsPDF()
  const lineHeight = 7
  let y = 20

  doc.setFontSize(20)
  doc.setTextColor(59, 130, 246)
  doc.text('SEO Score Analyzer Pro', 20, y)
  y += lineHeight * 2

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(`URL: ${report.url}`, 20, y)
  y += lineHeight
  doc.text(`Date: ${new Date(report.created_at).toLocaleDateString()}`, 20, y)
  y += lineHeight * 2

  doc.setFontSize(36)
  doc.setTextColor(report.score >= 80 ? 34 : report.score >= 50 ? 245 : 239, 
                   report.score >= 80 ? 197 : report.score >= 50 ? 158 : 68,
                   report.score >= 80 ? 94 : report.score >= 50 ? 11 : 68)
  doc.text(`Score: ${report.score}`, 20, y)
  y += lineHeight * 2

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Issues Found:', 20, y)
  y += lineHeight

  doc.setFontSize(10)
  doc.setTextColor(80)
  
  if (report.issues && report.issues.length > 0) {
    report.issues.forEach((issue, index) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(`${index + 1}. [${issue.type.toUpperCase()}] ${issue.title}`, 25, y)
      y += lineHeight
      const descLines = doc.splitTextToSize(issue.description, 160)
      descLines.forEach(line => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(line, 30, y)
        y += lineHeight - 1
      })
      y += 2
    })
  }

  y += lineHeight
  if (y > 250) {
    doc.addPage()
    y = 20
  }

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Recommendations:', 20, y)
  y += lineHeight

  doc.setFontSize(10)
  doc.setTextColor(80)
  
  if (report.recommendations && report.recommendations.length > 0) {
    report.recommendations.forEach((rec, index) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(`${index + 1}. [${rec.priority.toUpperCase()}] ${rec.title}`, 25, y)
      y += lineHeight
      const descLines = doc.splitTextToSize(rec.description, 160)
      descLines.forEach(line => {
        if (y > 270) {
          doc.addPage()
          y = 20
        }
        doc.text(line, 30, y)
        y += lineHeight - 1
      })
      y += 2
    })
  }

  y += lineHeight
  if (y > 250) {
    doc.addPage()
    y = 20
  }

  doc.setFontSize(14)
  doc.setTextColor(0)
  doc.text('Performance Metrics:', 20, y)
  y += lineHeight

  doc.setFontSize(10)
  doc.setTextColor(80)
  
  if (report.performance && report.performance.length > 0) {
    report.performance.forEach((perf) => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(`${perf.metric}: ${perf.value} (${perf.status})`, 25, y)
      y += lineHeight
    })
  }

  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text('Generated by SEO Score Analyzer Pro', 20, 285)

  doc.save(`seo-report-${report.id || 'analysis'}.pdf`)
}

export const exportToCSV = (report) => {
  const data = []

  data.push({
    Section: 'Summary',
    Type: 'URL',
    Title: report.url,
    Description: '',
    Value: '',
    Status: ''
  })

  data.push({
    Section: 'Summary',
    Type: 'Score',
    Title: report.score,
    Description: '',
    Value: '',
    Status: ''
  })

  data.push({
    Section: 'Summary',
    Type: 'Date',
    Title: new Date(report.created_at).toLocaleDateString(),
    Description: '',
    Value: '',
    Status: ''
  })

  if (report.issues) {
    report.issues.forEach(issue => {
      data.push({
        Section: 'Issues',
        Type: issue.type,
        Title: issue.title,
        Description: issue.description,
        Value: '',
        Status: ''
      })
    })
  }

  if (report.recommendations) {
    report.recommendations.forEach(rec => {
      data.push({
        Section: 'Recommendations',
        Type: rec.priority,
        Title: rec.title,
        Description: rec.description,
        Value: '',
        Status: ''
      })
    })
  }

  if (report.performance) {
    report.performance.forEach(perf => {
      data.push({
        Section: 'Performance',
        Type: '',
        Title: perf.metric,
        Description: '',
        Value: perf.value,
        Status: perf.status
      })
    })
  }

  const csv = Papa.unparse(data)
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const link = document.createElement('a')
  const url = URL.createObjectURL(blob)
  link.setAttribute('href', url)
  link.setAttribute('download', `seo-report-${report.id || 'analysis'}.csv`)
  link.style.visibility = 'hidden'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
}
